### ISSUE TITLE
Errors occurring when `generate_ticket` results passed into `create_ticket` override values with defaults.

### ISSUE THREAD

**Issue by zdc217** [cedarville-university/tdxlib#54]
Happy 4th!

We (Cybersecurity at University of Illinois) encountered an issue when using TDXTicketIntegration.generate_ticket() where default values were overriding what we passed in. We worked around this by passing in a dictionary to create_ticket(). 

We are up and running but we wanted to share this. Let us know if you have any questions. 

Thanks!
Zach Carrington and the U of I Cybersecurity Team

**Comment by nattyboyme3** [comment]
Hey Zach, 

Checking into this. Which values that you were supplying were being overridden? Were they in custom attributes or the parameters of the generate_ticket() method?

**Comment by edthedev** [comment]
@nattyboyme3 Here's what we supplied to the function:

```
    ticket_attributes = {
        'title_template':'test ticket',
        'ticket_type':292,
        'account':'None/Not found',
        'responsible':'buch1',
        'requestor':'buch1',
    }
 ticket = tdx.generate_ticket(**ticket_attributes)
```

Then when we called `create_ticket` passing in `ticket` from `generate_ticket`, we had problems with values being overridden.

As a work-around, we called `create_ticket` directly with a ticket created from raw JSON:
```python
        ticket = tdxlib.tdx_ticket.TDXTicket(tdx, {
            "AccountID": tdx.get_account_by_name(self.account_name)['ID'],
            "PriorityID": tdx.get_ticket_priority_by_name_id(param['priority'])['ID'],
            "RequestorUid": tdx.get_person_by_name_email(param['requestor_netid'])['UID'],
            "Title": param['title'],
            "TypeID": tdx.get_ticket_type_by_name_id(param['type'])['ID'],
        })
        response = tdx.create_ticket(ticket, silent=(not param['notify']))
```

We hope to revisit using `generate_ticket` once our new test environment is up. We will grab more details to share then if we still encounter this issue.
